# Generated by Django 5.2.4 on 2025-11-08 21:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('single_room', 'Single Room'), ('one_bedroom', 'One Bedroom'), ('two_bedroom', 'Two Bedroom'), ('three_bedroom', 'Three Bedroom')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('tenant', 'Tenant')], max_length=10)),
                ('user_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('total_floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('water_rate_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('rent_due', 'Rent Due'), ('payment_received', 'Payment Received'), ('payment_overdue', 'Payment Overdue'), ('water_bill', 'Water Bill'), ('maintenance', 'Maintenance'), ('general', 'General')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('floor_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_shower', models.BooleanField(default=True)),
                ('has_kitchen_unit', models.BooleanField(default=True)),
                ('has_clothes_cabinet', models.BooleanField(default=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rental_app.apartment')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rental_app.roomtype')),
            ],
            options={
                'ordering': ['floor_number', 'room_number'],
                'unique_together': {('apartment', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deposit_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposit_refunded', models.BooleanField(default=False)),
                ('deposit_refund_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('deposit_deduction_reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated'), ('suspended', 'Suspended'), ('switched', 'Switched Room')], default='active', max_length=20)),
                ('termination_reason', models.CharField(blank=True, choices=[('vacated', 'Tenant Vacated'), ('evicted', 'Evicted'), ('room_switch', 'Switched to Another Room'), ('other', 'Other')], max_length=20, null=True)),
                ('move_in_condition', models.TextField(blank=True)),
                ('move_out_condition', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='rental_app.apartment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to='rental_app.room')),
                ('switched_from_tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_tenancy', to='rental_app.tenancy')),
                ('switched_to_tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_tenancy', to='rental_app.tenancy')),
                ('tenant', models.ForeignKey(limit_choices_to={'user_type': 'tenant'}, on_delete=django.db.models.deletion.PROTECT, related_name='tenancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tenancies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa STK Push'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=20)),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('mpesa_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('months_covered', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_for_month', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('is_late_payment', models.BooleanField(default=False)),
                ('late_payment_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_payments', to='rental_app.apartment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_payments', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_payments', to='rental_app.tenancy')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='RentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('month_for', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('reported_to_office', models.BooleanField(default=False)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('report_notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_dues', to=settings.AUTH_USER_MODEL)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rent_dues', to='rental_app.tenancy')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rent_due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='rental_app.rentdue')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reports', to='rental_app.tenancy')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_month', models.DateField()),
                ('token_number', models.CharField(max_length=100, unique=True)),
                ('units_purchased', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='paid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_bills', to='rental_app.tenancy')),
            ],
            options={
                'ordering': ['-bill_month'],
            },
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_month', models.DateField()),
                ('units_consumed', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('current_reading', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_bills', to='rental_app.tenancy')),
            ],
            options={
                'ordering': ['-bill_month'],
            },
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['tenant', 'status'], name='rental_app__tenant__bd2533_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['apartment', 'status'], name='rental_app__apartme_6d053b_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['tenant', 'payment_date'], name='rental_app__tenant__4ec5db_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['apartment', 'payment_date'], name='rental_app__apartme_ee9fff_idx'),
        ),
        migrations.AddIndex(
            model_name='rentdue',
            index=models.Index(fields=['tenant', 'status'], name='rental_app__tenant__71b59d_idx'),
        ),
        migrations.AddIndex(
            model_name='rentdue',
            index=models.Index(fields=['due_date', 'status'], name='rental_app__due_dat_5a80d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentdue',
            unique_together={('tenancy', 'month_for')},
        ),
        migrations.AlterUniqueTogether(
            name='waterbill',
            unique_together={('tenancy', 'bill_month')},
        ),
    ]
